{% set name = "rush" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shenwei356/rush/archive/v{{ version }}.tar.gz
  sha256: 57450967bd222964f4865d7884b358d391e30d6eee8951b149f34f8642a32958

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - rush --help

about:
  home: https://github.com/shenwei356/rush
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary:  A cross-platform command-line tool for executing jobs in parallel

extra:
  recipe-maintainers:
    - apcamargo
